id: I34603B4A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T01:04:01+00:00'
last_modified: '2022-06-08T06:58:26.548924+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29649
  title: བསྡུས་སྒྲུང་རབ་སྙན་དྲི་ཟའི་པི་ཝང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    F7E2:
      image_group_id: I1KG17082
      title: ''
      total_pages: 252
      order: 1
      base_file: F7E2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
